-- Insert sample lab (linux-lab)
INSERT IGNORE INTO `labs` (
    `LabCode`, 
    `Title`, 
    `Subtitle`, 
    `Semester`, 
    `Logo`, 
    `DurationMinutes`, 
    `Credits`, 
    `Complexity`, 
    `Category`, 
    `Description`, 
    `Status`, 
    `TaskDefinition`, 
    `RuntimeType`, 
    `RuntimePort`, 
    `RuntimePath`, 
    `ContainerApiEnabled`, 
    `ContainerApiPort`,
    `DisplayOrder`,
    `IsDeleted`
) VALUES (
    'linux-lab',
    'Linux Administration Lab',
    'Bash Scripting & SysAdmin',
    'Semester 2',
    'default_linux_logo.png',
    60,
    25,
    'Beginner',
    'SysAdmin',
    'Practice Linux commands, file systems, and shell scripting in a secure Ubuntu environment.',
    'active',
    'vlab-dev-linux-task',
    'terminal',
    8080,
    '/',
    1,
    8080,
    1,
    0
);
